### ISSUE TITLE
Dumper does not close file/stream (?)

### ISSUE THREAD

**Issue by danielkasza** [kiith-sa/D-YAML#31]
Hello,

I might be missing something, but this code:

````
import std.stdio;
import dyaml.all;

void main()
{
    //Read the input.
    Node root = Loader("test.yaml").load();

    //Display the data read.
    foreach(string word; root["Hello World"])
    {
        writeln(word);
    }
    writeln("The answer is ", root["Answer"].as!int);

    //Dump the loaded document to output.yaml.
    Dumper("test.yaml").dump(root);
    
    //Read it again
    Node root2 = Loader("test.yaml").load();
}
````

Causes an exception on Windows because Dumper does not close the file when it finished dumping.
![image](https://cloud.githubusercontent.com/assets/11418469/7331251/91507330-ead6-11e4-912d-4d5fa1449b66.png)

- Is this intended behavior?
- How can I close the file?

My temporary workaround is a close method in Dumper.

Thanks

**Comment by kiith-sa** [comment]
Should be fixed by 385cfd5420db55803e876150c0c4bcdcae014f12 . Reopen the issue if this still happens.
